package e2b.enums;

public enum EScreenType {

 LOGIN_SCREEN, PROFILE_SETUP_SCREEN, PROFILE_SCREEN,
 ORDERS_SCREEN, HOME_SCREEN, MOBILE_VERIFICATION , OTP_CONFRM, STORE_INFO_SCREEN,Activity_SCREEN, GROUP_DETAIL_SCREEN,
 OTHER_PROFILE_SCREEN , GROUP_RIGHT_DRAWER_SCREEN , MEMBER_LIST_SCREEN

}
